MAP-1448 LocationResource file split accordingly with Test split MAP-…
ministryofjustice/hmpps-locations-inside-prison-api pull request #199
Opened 2024-08-01 14:42 UTC by marcusaleman

1 LocationInt.kt
Get Location info for {Id} and activate and deactivate.     Activate and de-Activate residential Location will be split later accordingly with the tests.

    @RequestMapping(“/locations" 
    @RequestMapping(“/locations/{id}”  
    @PutMapping("/{id}/deactivate/temporary")
    @PutMapping("/{id}/reactivate")
    @PutMapping("/{id}/update/temporary-deactivation")

    2 LocationKeyt.kt 
    Endpoints Manipulates Keys

   @GetMapping(“/key/{key}")
   @PostMapping("/keys", produces = [MediaType.APPLICATION_JSON_VALUE])
    
    3 LocationPrisonId.kt 
    Get information related with PrisonID (establishment)

    @GetMapping("/prison/{prisonId}")
    @GetMapping("prison/{prisonId}/groups")
    @GetMapping("prison/{prisonId}/group/{group}/location-prefix")
 
    @GetMapping("/prison/{prisonId}/inactive-cells")
    @GetMapping("/prison/{prisonId}/usage-type/{usageType}")
    @GetMapping("/prison/{prisonId}/location-type/{locationTYpe}”)
	
    4 LocationTransform.kt 
    Transform a LocationID (any kind of transformation) 
    
   @PutMapping("/{id}/used-for-type", produces = [MediaType.APPLICATION_JSON_VALUE]
   @PutMapping("/{id}/specialist-cell-types", produces = [MediaType.APPLICATION_JSON_VALUE])
   @PutMapping("/{id}/capacity")
    
    5 LocationResidential.kt DONE
    Residential and Non Residential manipulation. 
    Convert Cell Non Residential to Residential, etc.
    Create wing res or non res.

   @GetMapping("/residential-summary/{prisonId}")
   @PostMapping("/create-wing", produces = [MediaType.APPLICATION_JSON_VALUE]) 
   @PatchMapping("/residential/{id}")
   @PostMapping("/residential", produces = [MediaType.APPLICATION_JSON_VALUE])
   @PatchMapping(“/residential/{id}")
   @PostMapping("/non-residential", produces = [MediaType.APPLICATION_JSON_VALUE])
   @PutMapping(“/{id}/convert-cell-to-non-res-cell”)
   @PutMapping("/{id}/convert-to-cell")

2024-08-02 08:20 UTC, Mjwillis requested changes
All fine except should call them Resource at the end of the class name

2024-08-02 15:34 UTC, marcusaleman commented
@Mjwillis 
I have reopen the PR. May you check if it is ok, please?

2024-08-05 08:05 UTC, marcusaleman commented
hi, @Mjwillis  i need to go through with this PR with you to clear that part as i understand that it is a massive PR

2024-08-07 14:13 UTC, marcusaleman commented on src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/repository/LocationRepositoryTest.kt
> +      accommodationType = LocationResidentialResource.AllowedAccommodationTypeForConversion.NORMAL_ACCOMMODATION,
@Mjwillis 
Enum import fixed AllowedAccommodationTypeForConversion

2024-08-09 11:39 UTC, Mjwillis approved these changes
I'll merge

2024-08-09 11:39 UTC, merged